version: '3.9'
services:
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mysql
    ports:
        - "3306:3306"
    volumes:
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./db/mysql/:/var/lib/mysql
    networks:
      - aas-network

  adminer:
    image: adminer
    ports:
      - 8090:8080
    depends_on:
      - db
    networks:
      - aas-network

networks:
  aas-network:
    driver: bridge
